version: '3.4'

services:
  marketplaceapi:
    image: ${DOCKER_REGISTRY-}marketplaceapi
    build:
      context: .
      dockerfile: src/MarketPlaceApi/Dockerfile
    ports:
      - "8080:8080"
    networks:
      - my_shared_network_market

networks:
  my_shared_network_market:
    external: true